export const GET_ALL_GAMES = 'GET_ALL_PRODUCTS';
export const GET_GAME_DETAIL = 'GET_GAME_DETAIL';
export const CREATE_GAME = 'CREATE_GAME';
export const CLEAR_GAME_DETAIL = 'CLEAR_GAME_DETAIL';
export const GET_ALL_GENRES = 'GET_ALL_GENRES';
export const SEARCH_GAMES = 'SEARCH_GAMES';
export const UPDATE_FILTER_STORE = 'UPDATE_FILTER_STORE';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const CLEAR_FILTER_GAME = 'CLEAR_FILTER_GAME';
export const FILTER_GAMES_DB_API = 'FILTER_GAMES_DB_API';

