export const GET_ALL_GAMES = 'GET_ALL_PRODUCTS';
export const GET_GAME_DETAIL = 'GET_GAME_DETAIL';
export const CREATE_GAME = 'CREATE_GAME';
export const CLEAR_GAME_DETAIL = 'CLEAR_GAME_DETAIL';
export const GET_ALL_GENRES = 'GET_ALL_GENRES';
export const SEARCH_GAMES = 'SEARCH_GAMES';
export const FILTER_GAMES = 'FILTER_GAMES';

